# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-05 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image_path', models.ImageField(upload_to='profile/')),
                ('result1_name', models.CharField(max_length=128)),
                ('result2_name', models.CharField(max_length=128)),
                ('result3_name', models.CharField(max_length=128)),
                ('result1_value', models.IntegerField(default=0)),
                ('result2_value', models.IntegerField(default=0)),
                ('result3_value', models.IntegerField(default=0)),
            ],
        ),
    ]
