# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-05 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_auto_20170805_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='upload_image_path',
            new_name='upload_image',
        ),
    ]
